"""Frozen challenge levels generated once and verified with the core rules."""

from game.levels import arrow
from game.models import Direction, Level


EXTRA_LEVELS: tuple[Level, ...] = (
    Level(
        id=4,
        name="交错航线",
        rows=8,
        cols=8,
        arrows=(
            arrow("A", 7, 3, Direction.UP),
            arrow("B", 0, 3, Direction.UP),
            arrow("C", 2, 4, Direction.LEFT),
            arrow("D", 2, 1, Direction.UP),
            arrow("E", 1, 1, Direction.RIGHT),
            arrow("F", 1, 2, Direction.DOWN),
            arrow("G", 4, 2, Direction.LEFT),
            arrow("H", 4, 1, Direction.DOWN),
            arrow("I", 6, 1, Direction.DOWN),
            arrow("J", 7, 1, Direction.DOWN),
            arrow("K", 5, 1, Direction.LEFT),
            arrow("L", 5, 0, Direction.DOWN),
            arrow("M", 6, 0, Direction.DOWN),
            arrow("N", 7, 0, Direction.LEFT),
            arrow("O", 4, 3, Direction.RIGHT),
            arrow("P", 4, 5, Direction.UP),
            arrow("Q", 3, 5, Direction.LEFT),
            arrow("R", 3, 4, Direction.DOWN),
            arrow("S", 7, 4, Direction.DOWN),
            arrow("T", 5, 4, Direction.RIGHT),
            arrow("U", 5, 6, Direction.RIGHT),
            arrow("V", 5, 7, Direction.UP),
            arrow("W", 4, 7, Direction.UP),
            arrow("X", 3, 7, Direction.RIGHT),
        ),
        solution_order=tuple("XWVUTSRQPONMLKJIHGFEDCBA"),
        par_seconds=140,
        difficulty="困难",
        pack="challenge",
    ),
    Level(
        id=5,
        name="环形拆解",
        rows=8,
        cols=8,
        arrows=(
            arrow("A", 2, 5, Direction.RIGHT),
            arrow("B", 2, 6, Direction.RIGHT),
            arrow("C", 2, 7, Direction.DOWN),
            arrow("D", 6, 7, Direction.DOWN),
            arrow("E", 7, 7, Direction.LEFT),
            arrow("F", 7, 3, Direction.LEFT),
            arrow("G", 7, 2, Direction.UP),
            arrow("H", 6, 2, Direction.UP),
            arrow("I", 5, 2, Direction.LEFT),
            arrow("J", 5, 1, Direction.UP),
            arrow("K", 4, 1, Direction.LEFT),
            arrow("L", 4, 0, Direction.LEFT),
            arrow("M", 5, 0, Direction.LEFT),
            arrow("N", 3, 1, Direction.RIGHT),
            arrow("O", 3, 2, Direction.RIGHT),
            arrow("P", 3, 3, Direction.UP),
            arrow("Q", 1, 3, Direction.RIGHT),
            arrow("R", 1, 4, Direction.RIGHT),
            arrow("S", 1, 6, Direction.UP),
            arrow("T", 0, 6, Direction.UP),
            arrow("U", 2, 2, Direction.UP),
            arrow("V", 1, 2, Direction.UP),
            arrow("W", 0, 2, Direction.LEFT),
            arrow("X", 0, 1, Direction.LEFT),
            arrow("Y", 0, 0, Direction.UP),
            arrow("Z", 4, 2, Direction.RIGHT),
            arrow("AA", 4, 6, Direction.DOWN),
            arrow("AB", 7, 6, Direction.DOWN),
        ),
        solution_order=(
            "AB", "AA", "Z", "Y", "X", "W", "V", "U", "T", "S", "R",
            "Q", "P", "O", "N", "M", "L", "K", "J", "I", "H", "G",
            "F", "E", "D", "C", "B", "A",
        ),
        par_seconds=170,
        difficulty="困难",
        pack="challenge",
    ),
    Level(
        id=6,
        name="星轨迷阵",
        rows=8,
        cols=8,
        arrows=(
            arrow("A", 3, 0, Direction.LEFT),
            arrow("B", 6, 1, Direction.DOWN),
            arrow("C", 7, 1, Direction.RIGHT),
            arrow("D", 7, 6, Direction.DOWN),
            arrow("E", 5, 4, Direction.UP),
            arrow("F", 4, 4, Direction.RIGHT),
            arrow("G", 4, 5, Direction.RIGHT),
            arrow("H", 4, 6, Direction.UP),
            arrow("I", 3, 6, Direction.UP),
            arrow("J", 1, 6, Direction.UP),
            arrow("K", 0, 6, Direction.LEFT),
            arrow("L", 0, 3, Direction.DOWN),
            arrow("M", 1, 3, Direction.DOWN),
            arrow("N", 4, 3, Direction.LEFT),
            arrow("O", 4, 2, Direction.DOWN),
            arrow("P", 6, 2, Direction.RIGHT),
            arrow("Q", 6, 3, Direction.RIGHT),
            arrow("R", 6, 5, Direction.DOWN),
            arrow("S", 7, 5, Direction.DOWN),
            arrow("T", 6, 7, Direction.UP),
            arrow("U", 4, 7, Direction.UP),
            arrow("V", 2, 7, Direction.RIGHT),
            arrow("W", 6, 4, Direction.DOWN),
            arrow("X", 7, 4, Direction.DOWN),
            arrow("Y", 2, 6, Direction.LEFT),
            arrow("Z", 2, 3, Direction.LEFT),
            arrow("AA", 2, 0, Direction.UP),
            arrow("AB", 1, 0, Direction.LEFT),
            arrow("AC", 2, 4, Direction.UP),
            arrow("AD", 1, 4, Direction.UP),
            arrow("AE", 0, 4, Direction.UP),
            arrow("AF", 0, 0, Direction.UP),
        ),
        solution_order=(
            "AF", "AE", "AD", "AC", "AB", "AA", "Z", "Y", "X", "W",
            "V", "U", "T", "S", "R", "Q", "P", "O", "N", "M", "L",
            "K", "J", "I", "H", "G", "F", "E", "D", "C", "B", "A",
        ),
        par_seconds=210,
        difficulty="专家",
        pack="challenge",
    ),
)
